name: Train on Videos

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - run: npm ci
      
      - name: Training on Videos
        run: npm run train
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
          UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}